export const HTTP_ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  DUPLICATED_KEY_ERROR: 'DUPLICATED_KEY_ERROR',
  NEED_SET_NICKNAME: 'NEED_SET_NICKNAME',
  NEED_SET_ADDRESS: 'NEED_SET_ADDRESS',
  NEED_SET_GENDER: 'NEED_SET_GENDER',
  VALIDATED_ERROR: 'VALIDATED_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SQL_SYNTAX_ERROR: 'SQL_SYNTAX_ERROR',
  MAXIMUM_SETTLED_ADDRESS: 'MAXIMUM_SETTLED_ADDRESS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};
