export const HTTP_ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATED_KEY_ERROR: 'DUPLICATED_KEY_ERROR',
  NEED_SET_NICKNAME: 'NEED_SET_NICKNAME',
  NEED_SET_ADDRESS: 'NEED_SET_ADDRESS',
  VALIDATED_ERROR: 'VALIDATED_ERROR',
};
